### ISSUE TITLE
Pick split direction based on aspect ratio

### ISSUE THREAD

**Issue by haasn** [benweitzman/BinarySpacePartition#4]
I use both portrait mode and landscape mode monitors, and the default split direction being vertical is a bit annoying on the portrait mode monitors.

Would it be possible to have the split direction be based on the current window's aspect ratio instead? Ie. if the window is wider than it is tall, it would split vertically, and so on.

This seems like it would lend itself better to binary space partitioning than the “alternating” scheme, too.

**Comment by benweitzman** [comment]
Nice idea. I'll have to update this repo with some upstream changes and then I'll implement

**Comment by haasn** [comment]
Thanks!
